Analyses Queued:
  Fischer: false
  Mageck:
    Bottom_Sorted: true
    Top_Sorted: true
  Ratio: false
Input File Paths:
  Control: /Users/collinschlager/Documents/Rohatgi_Lab/Informatics/screen_analyzer/tmp/data/Control/Brie_kinome_controls.txt
  Fastq:
    Rep1:
      Bottom Sorted Population: /Users/collinschlager/Documents/Rohatgi_Lab/Informatics/screen_analyzer/tmp/data/Fastq/100mM-rep1-Bot5_S2_L001_R1_001.fastq
      Top Sorted Population: /Users/collinschlager/Documents/Rohatgi_Lab/Informatics/screen_analyzer/tmp/data/Fastq/100mM-rep1-Top5_S3_L001_R1_001.fastq
      Unsorted Population: /Users/collinschlager/Documents/Rohatgi_Lab/Informatics/screen_analyzer/tmp/data/Fastq/100mM-rep1-Unsorted_S1_L001_R1_001.fastq
  Library: /Users/collinschlager/Documents/Rohatgi_Lab/Informatics/screen_analyzer/tmp/data/Library/Mouse_kinome_list_brie_updated.csv
Input Files:
  Control: Brie_kinome_controls.txt
  Fastq:
    Rep1:
      Bottom Sorted Population: 100mM-rep1-Bot5_S2_L001_R1_001.fastq
      Top Sorted Population: 100mM-rep1-Top5_S3_L001_R1_001.fastq
      Unsorted Population: 100mM-rep1-Unsorted_S1_L001_R1_001.fastq
  Library: Mouse_kinome_list_brie_updated.csv
Metadata:
  Analysis Name: mageck_analysis
  Analysis Path: /Users/collinschlager/Documents/Rohatgi_Lab/Informatics/screen_analyzer/tmp/Screen_Analyses/mageck_analysis
  Notes: null
  Replicates: 1
  Timestamp: '1533956237702'
